[package]
name = "sharded-counter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.13.0"

[dev-dependencies]
clap = { version = "3.2.16", features = ["derive"] }
itertools = "0.10.3"
